services:
  - type: web
    name: code-pilot-server
    env: docker
    dockerfilePath: server/Dockerfile
    dockerContext: server
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: PORT
        value: 8000
